config/routes.rb
Onemyday::Application.routes.draw do

  root to: 'home#index'

  resources :users do
    get 'activities', to: "activities#index", on: :member
    get 'unseen_activities_count', to: "activities#unseen_activities_count", on: :member
  end

  get '/edit_current_user', to: "users#edit_current"
  get '/update_avatar_facebook', to: "users#update_avatar_facebook"
  get '/update_avatar_twitter', to: "users#update_avatar_twitter"
  post '/upload_user_avatar', to: 'users#upload_avatar'

  resources :stories do
    get 'comments', on: :member
    get 'likes', on: :member
  end
  post '/upload_story_photo', to: 'stories#upload_photo'
  post '/publish', to: 'stories#publish'
  get '/search_stories', to: 'stories#search'
  post '/new_like', to: 'stories#like'
  post '/unlike', to: 'stories#unlike'
  get '/explore', to: 'stories#explore'

  get '/tags', to: 'tags#index'

  resources :comments

  resources :relationships, only: [:create, :destroy]

  resources :story_photos, only: [:destroy, :update]

  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get '/:user_id/stories/feed', to: 'user_stories#feed', as: :feed
  get '/:user_id/stories/own', to: 'user_stories#own', as: :own_stories
  get '/:user_id/stories/liked', to: 'user_stories#liked', as: :liked_stories
  get '/:user_id/stories/unfinished', to: 'user_stories#unfinished', as: :unfinished_stories

  get '/channel.html', to: 'static_pages#channel'
  get '/landing', to: 'static_pages#landing'
  get '/contacts', to: 'static_pages#contacts'
  get '/terms', to: 'static_pages#terms'

  post 'auth/regular', to: "sessions#create", as: :regular_sign_in
  match 'auth/:provider/callback', to: 'sessions#create'
  post 'auth/:provider/destroy', to: 'sessions#destroy_auth', as: :auth_destroy

  get '/invite_friends', to: "invite_friends#index", as: :invite_friends

  scope module: "api" do
    post '/api/sessions/social_auth', to: 'sessions#social_auth'

    post '/api/stories/create_and_publish', to: 'stories#create_and_publish'
    post '/api/stories/:id/like', to: 'stories#like'
    post '/api/stories/:id/unlike', to: 'stories#unlike'
    post '/api/stories/:id/update', to: 'stories#update'

    post '/api/comments/create', to: 'comments#create'
    post '/api/comments/:id/destroy', to: 'comments#destroy'

    post '/api/users/:id/update', to: 'users#update'
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :text

  belongs_to :story, counter_cache: true
  belongs_to :comment
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :activities, as: :trackable, dependent: :destroy

  validates_presence_of :text
  validates :user, presence: true
  validates :story, presence: true

  scope :by_date, -> { order("created_at") }

  def created_at_nice
    Comment.created_at_nice created_at
  end

  def self.created_at_nice date
    date.try(:strftime, "%b %d %Y at %H:%M")
  end

  # Override getter method for document association
  def story_with_unscoped
    # Fetch document with default scope disabled
    Story.unscoped { story_without_unscoped }
  end
  alias_method_chain :story, :unscoped

end

app/controllers/api/comments_controller.rb
class Api::CommentsController < Api::ApiController

  def create
    begin
      creator = User.find(params[:creator_id])
      comment = CommentsService.create(params, creator)
      render json: comment
    rescue => e
      render json: {message: e.message, backtrace: e.backtrace}
    end
  end

  def destroy
    begin
      comment = Comment.find(params[:id])
      comment.destroy
      render json: {success: true}
    rescue => e
      render json: {message: e.message, backtrace: e.backtrace}
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  include CommentsHelper

  before_filter :signed_in_user_filter

  def create
    @comment = CommentsService.create(params, current_user)
    respond_to { |t| t.js }
  end

  def update
    @comment = Comment.find(params[:comment][:id])

    if comment_editable? @comment
      @comment.text = params[:comment][:text]
      @comment.save!
      respond_to { |t| t.js }
    end
  end

  def destroy
    @comment = Comment.find(params[:id])

    if comment_deletable? @comment
      @comment.destroy
      respond_to { |t| t.js }
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper

  # comments are deletable by owners and by owners of stories on which comment has been posted on.
  def comment_deletable?(comment)
    current_user && (comment_owner?(comment) || story_owner?(comment))
  end

  # comments are editable only by users who owns them
  def comment_editable?(comment)
    current_user && comment_owner?(comment)
  end

  def comment_owner?(comment)
    current_user && comment.user.id == current_user.id
  end

  def story_owner?(comment)
    current_user && comment.story.user.id == current_user.id
  end

end

app/views/comments/_comment.slim
div.comment class="#{defined?(clazz) ? clazz : ""}" id="comment#{comment.id}" data-comment-id="#{comment.id}"
  input.edit-comment-action type="hidden" value="#{comment_path comment}"
  div.commentHeader
    = image_tag comment.user.avatar.url(:thumb), title: "#{comment.user.name}", width: 32
    a.author href="#{user_path comment.user.id}" #{comment.user.name}
    span.time #{comment.created_at_nice}
  p.text
    = comment.text
  div.controls
    - if comment_editable? comment
      a href="#" onclick="App.comments.edit(this); return false;" = t '.edit'
    - if comment_deletable? comment
      a data-remote="true" href="#{comment_path comment}" data-method="DELETE" = t '.remove'

app/views/comments/create.js.erb
var anyErrors = <%= @comment.errors.any? %>;
if (!anyErrors) {
    var comment = "<%= escape_javascript(render 'comment', comment: @comment) %>";
    if ($("#commentsContainer .comment").length == 0) {
        $("#commentsContainer").prepend(comment);
    } else {
        $("#commentsContainer .comment:last").after(comment);
    }

    $("#commentsContainer textarea").val("");
} else {
    alert("Oh, no :(");
}

app/views/comments/destroy.js.erb
$("#comment<%= @comment.id %>").remove();

app/views/comments/update.js.erb
var anyErrors = <%= @comment.errors.any? %>;
if (!anyErrors) {
    var comment = "<%= escape_javascript(render 'comment', comment: @comment) %>";

    $("#comment<%= @comment.id %>").replaceWith(comment);
}

App.comments.revertEdit();