config/routes.rb
Onemyday::Application.routes.draw do

  root to: 'home#index'

  resources :users do
    get 'activities', to: "activities#index", on: :member
    get 'unseen_activities_count', to: "activities#unseen_activities_count", on: :member
  end

  get '/edit_current_user', to: "users#edit_current"
  get '/update_avatar_facebook', to: "users#update_avatar_facebook"
  get '/update_avatar_twitter', to: "users#update_avatar_twitter"
  post '/upload_user_avatar', to: 'users#upload_avatar'

  resources :stories do
    get 'comments', on: :member
    get 'likes', on: :member
  end
  post '/upload_story_photo', to: 'stories#upload_photo'
  post '/publish', to: 'stories#publish'
  get '/search_stories', to: 'stories#search'
  post '/new_like', to: 'stories#like'
  post '/unlike', to: 'stories#unlike'
  get '/explore', to: 'stories#explore'

  get '/tags', to: 'tags#index'

  resources :comments

  resources :relationships, only: [:create, :destroy]

  resources :story_photos, only: [:destroy, :update]

  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get '/:user_id/stories/feed', to: 'user_stories#feed', as: :feed
  get '/:user_id/stories/own', to: 'user_stories#own', as: :own_stories
  get '/:user_id/stories/liked', to: 'user_stories#liked', as: :liked_stories
  get '/:user_id/stories/unfinished', to: 'user_stories#unfinished', as: :unfinished_stories

  get '/channel.html', to: 'static_pages#channel'
  get '/landing', to: 'static_pages#landing'
  get '/contacts', to: 'static_pages#contacts'
  get '/terms', to: 'static_pages#terms'

  post 'auth/regular', to: "sessions#create", as: :regular_sign_in
  match 'auth/:provider/callback', to: 'sessions#create'
  post 'auth/:provider/destroy', to: 'sessions#destroy_auth', as: :auth_destroy

  get '/invite_friends', to: "invite_friends#index", as: :invite_friends

  scope module: "api" do
    post '/api/sessions/social_auth', to: 'sessions#social_auth'

    post '/api/stories/create_and_publish', to: 'stories#create_and_publish'
    post '/api/stories/:id/like', to: 'stories#like'
    post '/api/stories/:id/unlike', to: 'stories#unlike'
    post '/api/stories/:id/update', to: 'stories#update'

    post '/api/comments/create', to: 'comments#create'
    post '/api/comments/:id/destroy', to: 'comments#destroy'

    post '/api/users/:id/update', to: 'users#update'
  end
end

app/views/shared/_error_messages.slim
div#form_errors_div
  - if defined?(object) && object && object.errors.any?
    div.alert.alert-error
      = t '.header'
      ul
        - object.errors.each do |key, msg|
          li.errorLi data-field-id="#{key}"
            = msg

app/views/shared/_show_user_small.slim
div.likeblock class="#{cycle("odd", "even")}"
  a.fl href="#{user_path user.id}"
    = image_tag user.avatar.url(:small), title: user.name
  a.username href="#{user_path user.id}"
    h3 = user.name
  div.fr
    = render "users/follow_form", user: user
  div style='clear:both;'

app/views/shared/_sign_in.slim
div#signInModal.fade.modal.hide class="#{@locale}"
  button type="button" class="close" data-dismiss="modal" ×
  div.modal-header.open-sans
    h3 = t '.sign_in_header'
  div.modal-body
    a.social-link.social-facebook href="/auth/facebook"
      div
    - if @locale == "ru"
      a.social-link.social-vkontakte href="/auth/vkontakte"
        div
    a.social-link.social-twitter href="/auth/twitter"
      div
    div style="clear:both;"
    div.signInHeader
      div.text = t '.or'
      div.border
    div.explanation = t ".exp"
    = form_tag regular_sign_in_path, class:"signInForm", remote:true, onsubmit:"return App.home.onLoginSubmit();" do
      div#loginError.loginError
      div.mb10
        label = t '.email'
        input#loginEmail.long name="email" req="req" type="text" data-err-text="#{t '.email_err'}"
      div.mb10
        label = t '.password'
        input#loginPassword.long name="password" req="req" type="password" data-err-text="#{t '.password_err'}"
      div
        label
        input.fr.smb.btn.btn-large.btn-foxtrot data-loading-text="#{t ".submiting"}" data-complete-text="#{t ".submit"}" type="submit" value="#{t ".submit"}"