config/routes.rb
Onemyday::Application.routes.draw do

  root to: 'home#index'

  resources :users do
    get 'activities', to: "activities#index", on: :member
    get 'unseen_activities_count', to: "activities#unseen_activities_count", on: :member
  end

  get '/edit_current_user', to: "users#edit_current"
  get '/update_avatar_facebook', to: "users#update_avatar_facebook"
  get '/update_avatar_twitter', to: "users#update_avatar_twitter"
  post '/upload_user_avatar', to: 'users#upload_avatar'

  resources :stories do
    get 'comments', on: :member
    get 'likes', on: :member
  end
  post '/upload_story_photo', to: 'stories#upload_photo'
  post '/publish', to: 'stories#publish'
  get '/search_stories', to: 'stories#search'
  post '/new_like', to: 'stories#like'
  post '/unlike', to: 'stories#unlike'
  get '/explore', to: 'stories#explore'

  get '/tags', to: 'tags#index'

  resources :comments

  resources :relationships, only: [:create, :destroy]

  resources :story_photos, only: [:destroy, :update]

  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get '/:user_id/stories/feed', to: 'user_stories#feed', as: :feed
  get '/:user_id/stories/own', to: 'user_stories#own', as: :own_stories
  get '/:user_id/stories/liked', to: 'user_stories#liked', as: :liked_stories
  get '/:user_id/stories/unfinished', to: 'user_stories#unfinished', as: :unfinished_stories

  get '/channel.html', to: 'static_pages#channel'
  get '/landing', to: 'static_pages#landing'
  get '/contacts', to: 'static_pages#contacts'
  get '/terms', to: 'static_pages#terms'

  post 'auth/regular', to: "sessions#create", as: :regular_sign_in
  match 'auth/:provider/callback', to: 'sessions#create'
  post 'auth/:provider/destroy', to: 'sessions#destroy_auth', as: :auth_destroy

  get '/invite_friends', to: "invite_friends#index", as: :invite_friends

  scope module: "api" do
    post '/api/sessions/social_auth', to: 'sessions#social_auth'

    post '/api/stories/create_and_publish', to: 'stories#create_and_publish'
    post '/api/stories/:id/like', to: 'stories#like'
    post '/api/stories/:id/unlike', to: 'stories#unlike'
    post '/api/stories/:id/update', to: 'stories#update'

    post '/api/comments/create', to: 'comments#create'
    post '/api/comments/:id/destroy', to: 'comments#destroy'

    post '/api/users/:id/update', to: 'users#update'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    respond_to do |format|
      @recent_stories = Story.recent.paginate(page: params[:page])
      format.html {
        @top_stories = Story.top_for_home 3
      }
      format.js
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/header.slim
input#processingImages type="hidden" value="#{t '.processing_images'}"
input#preparingImages type="hidden" value="#{t '.preparing_images'}"

header.navbar.navbar-fixed-top
  div.navbar-inner
    div.container
      a.logo href="/"

      ul.navigation.ib.exploreNav
        li.tellNav
          = link_to "#{t '.explore'}", explore_path, class: "navLink"

      div.navbarInner
        = form_tag search_stories_path, method: "GET", onsubmit:"return App.home.onSearchSubmit()" do
          input#navbarSearch.imLookingFor name="q" type="text" placeholder="#{t '.search_placeholder'}"
          a.magnifier href="#" data-submitable="true": img src="/assets/magnifier.gif" alt=""

      ul.navigation.fr
        - if current_user
          li.tellNav
            = link_to "#{t '.tell'}", new_story_path, class: "navLink"
          li#userMenu.btn-group.userNav
            a.navLink.dropdown-toggle data-toggle="dropdown" href="#{user_path current_user}"
              = image_tag current_user.avatar.url :thumb, class: 'navbarAvatar'
              - if current_user.activities.unseen.present?
                span.user-activity-count #{current_user.activities.unseen.size}
              span.username = current_user.name
              span.caret
            ul#userDropdown.dropdown-menu
              li
                = link_to "#{t '.edit_profile'}", edit_current_user_path
              li
                = link_to "#{t '.invite_friends'}", invite_friends_path
              li
                = link_to "#{t '.contacts'}", contacts_path
              li
                = link_to "#{t '.sign_out'}", signout_path
        - else
          li
            a.navLink href="#{contacts_path}" = t '.contacts'
            a.navLink data-toggle="modal" href="#signInModal" = t '.sign_in'

app/views/home/index.js.erb
$("body").append("<div id='tempStories' class='hide'>#{<%= j render "/stories/list_stories_inner", stories: @recent_stories %>}</div>");
var newItems = $("#tempStories > .smallStory");
$('#recentStories .storiesContainer').append(newItems).masonry('appended', newItems, true);
$("#tempStories").remove();
<% if @recent_stories.next_page %>
    $('.pagination').replaceWith('<%= j will_paginate(@recent_stories) %>');
<% else %>
    $('.pagination').html("");
<% end %>

app/views/home/index.slim
- if current_user && current_user.stories.length == 0 && !cookies[:hide_story_message]
  div.photoHeader.photoHeader2
    div.innerContainer
      div.cont
        = t '.tell_story_header'
        br
        a.btn.btn-large.createButton.open-sans href="#{new_story_path}" = t '.tell_story'
        span.hideMessage
          = t '.or_html'
          a href="#" onclick="App.home.hideStoryMessage();return false;" = t '.hide_message'

  div.photoHeaderSpan

- unless current_user
  div.photoHeader
    div.innerContainer
      div.cont
        = t '.onemyday_desc'
        br
        a.btn.btn-large.createButton.open-sans data-toggle="modal" href="#signInModal" = t '.sign_up'
  div.photoHeaderSpan

div
  h2.homeHeader = t '.pop_stories_html'
  a href="#{explore_path}?ft=#{StoriesHelper::EXPLORE_FILTER_POPULAR}" = t '.view_all_html'
  = render "/stories/list_stories", stories: @top_stories

  div.homeTags
    div.ib
      h2.headerCaption = t '.pop'
      h2.headerCaption = t '.tags_html'

    div.ib.onemyday-bgroup.btn-group
      - get_popular_tags.each do |tag|
        a.btn href="#{explore_path}?t=#{tag.name}" #{tag.name.capitalize}

  h2.homeHeader = t '.recent_stories_html'
  a href="#{explore_path}?ft=#{StoriesHelper::EXPLORE_FILTER_RECENT}" = t '.view_all_html'
  div#recentStories
    = render "/stories/list_stories", stories: @recent_stories

  div style="clear:both;"
  = will_paginate @recent_stories