config/routes.rb
Onemyday::Application.routes.draw do

  root to: 'home#index'

  resources :users do
    get 'activities', to: "activities#index", on: :member
    get 'unseen_activities_count', to: "activities#unseen_activities_count", on: :member
  end

  get '/edit_current_user', to: "users#edit_current"
  get '/update_avatar_facebook', to: "users#update_avatar_facebook"
  get '/update_avatar_twitter', to: "users#update_avatar_twitter"
  post '/upload_user_avatar', to: 'users#upload_avatar'

  resources :stories do
    get 'comments', on: :member
    get 'likes', on: :member
  end
  post '/upload_story_photo', to: 'stories#upload_photo'
  post '/publish', to: 'stories#publish'
  get '/search_stories', to: 'stories#search'
  post '/new_like', to: 'stories#like'
  post '/unlike', to: 'stories#unlike'
  get '/explore', to: 'stories#explore'

  get '/tags', to: 'tags#index'

  resources :comments

  resources :relationships, only: [:create, :destroy]

  resources :story_photos, only: [:destroy, :update]

  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get '/:user_id/stories/feed', to: 'user_stories#feed', as: :feed
  get '/:user_id/stories/own', to: 'user_stories#own', as: :own_stories
  get '/:user_id/stories/liked', to: 'user_stories#liked', as: :liked_stories
  get '/:user_id/stories/unfinished', to: 'user_stories#unfinished', as: :unfinished_stories

  get '/channel.html', to: 'static_pages#channel'
  get '/landing', to: 'static_pages#landing'
  get '/contacts', to: 'static_pages#contacts'
  get '/terms', to: 'static_pages#terms'

  post 'auth/regular', to: "sessions#create", as: :regular_sign_in
  match 'auth/:provider/callback', to: 'sessions#create'
  post 'auth/:provider/destroy', to: 'sessions#destroy_auth', as: :auth_destroy

  get '/invite_friends', to: "invite_friends#index", as: :invite_friends

  scope module: "api" do
    post '/api/sessions/social_auth', to: 'sessions#social_auth'

    post '/api/stories/create_and_publish', to: 'stories#create_and_publish'
    post '/api/stories/:id/like', to: 'stories#like'
    post '/api/stories/:id/unlike', to: 'stories#unlike'
    post '/api/stories/:id/update', to: 'stories#update'

    post '/api/comments/create', to: 'comments#create'
    post '/api/comments/:id/destroy', to: 'comments#destroy'

    post '/api/users/:id/update', to: 'users#update'
  end
end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :title, :published, :story_photos_attributes, :tag_list, :reported_for

  attr_accessor :current_user

  acts_as_taggable

  belongs_to :user

  has_many :story_elements, dependent: :destroy
  has_many :story_photos, :through => :story_elements, :source => :element, :source_type => 'StoryPhoto',
           dependent: :destroy
  has_many :story_texts, :through => :story_elements, :source => :element, :source_type => 'StoryText',
           dependent: :destroy

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :views, dependent: :destroy
  accepts_nested_attributes_for :story_photos

  has_many :activities, as: :trackable, dependent: :destroy

  validates_presence_of :title
  validates :user, presence: true

  self.per_page = 10

  default_scope where(:published => true)
  scope :unpublished, where(:published => false)
  scope :recent, ->(tags=nil) {
    stories = Story.scoped
    stories = tagged_with(tags) if tags
    stories.order("created_at DESC")
  }
  scope :from_users_followed_by, lambda { |user| followed_by(user) }

  def initialize(attributes = nil, options = {})
    super attributes, options
    self.published = false
  end

  def before_save
    self.published = false if self.story_photos.blank?
  end

  def has_photos
    self.story_photos.any?
  end

  def date_nice_text
    Story.date_to_nice_text created_at
  end

  def self.date_to_text(time)
    I18n.localize time, format: "%d-%m-%Y"
  end

  def self.date_to_nice_text(time)
    I18n.localize time, format: "%b %d, %Y"
  end

  def self.top(lim=nil, tags=nil)
    if tags
      # I had to use two selects because for some reason JOINING tags doesn't work with additional agg_count column.
      stories = Story.scoped.tagged_with(tags)
      Story.select("*, (likes_count * 10) + views_count as agg_count").
          where("stories.id in (#{stories.collect { |story| story.id }.join(",")})",).
          order("agg_count DESC").limit(lim) if stories.any?
    else
      Story.select("*, (likes_count * 10) + views_count as count").order("count DESC").limit(lim)
    end
  end

  def self.top_for_home(lim)
    stories = []
    (1..5).each do |i|
      t = (2 * i).weeks.ago
      stories = top_with_time(lim, t)
      break if stories.count > 0
    end
    stories
  end

  def is_liked_by_user(user=nil)
    user ||= current_user
    return unless user
    self.likes.pluck(:user_id).include?(user.id)
  end

  def meta_tags
    tags.join ", "
  end

  def meta_description
    "#{title}. Onemyday"
  end

  private

  def self.top_with_time(lim, time_ago)
    Story.select("*, (comments_count * 15) + (likes_count * 10) + views_count as count")
         .where("created_at > ?", time_ago).order("count DESC").limit(lim)
  end

  # Returns an SQL condition for users followed by the given user.
  # We include the user's own id as well.
  def self.followed_by(user)
    followed_user_ids = %(SELECT followed_id FROM relationships
                            WHERE follower_id = :user_id)
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          {user_id: user})
  end

end

app/controllers/api/stories_controller.rb
class Api::StoriesController < Api::ApiController
  def like
    begin
      story = Story.find(params[:id])
      like = story.likes.build(user_id: params[:user_id])
      like.save!
      ActivityTracking.track like, story.user
      render json: {success: true}
    rescue => e
      render json: {message: e.message, backtrace: e.backtrace}
    end
  end

  def unlike
    begin
      Story.find(params[:id]).likes.find_by_user_id(params[:user_id]).destroy
      render json: {success: true}
    rescue => e
      render json: {message: e.message, backtrace: e.backtrace}
    end
  end

  def update
    begin
      Story.find(params[:id]).update_attributes(params[:story])
      render json: {success: true}
    rescue => e
      render json: {message: e.message, backtrace: e.backtrace}
    end
  end

  def create_and_publish
    begin
      user = User.find(params[:author_id])
      story = user.stories.build(params[:story])
      story.published = true
      params[:story_photos].each do |story_photo|
        story_photo[:orientation] = 1 unless story_photo[:orientation]
        story.story_photos.build story_photo
      end
      params[:story_texts] && params[:story_texts].each do |story_text|
          story.story_texts.build story_text
      end
      story.save

      if story.valid?
        render json: {story_id: story.id, status: "success"}
      else
        render json: {errors: story.errors, status: "bad_request"}
      end
    rescue => e
      render json: {message: e.message, backtrace: e.backtrace}
    end
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  before_filter :signed_in_user_filter, except: [:show, :search, :explore, :index, :comments, :likes]

  def index
    @stories = Story.all

    respond_to do |f|
      f.json { render :json => StoryFormat.to_json(@stories, params) }
    end
  end

  def search
    @query = params[:q]

    filter_type = params[:ft].blank? ? StoriesHelper::EXPLORE_FILTER_RECENT : params[:ft].to_i

    @tag = @query.slice(1, @query.length) if @query && @query.start_with?("#")

    if filter_type == StoriesHelper::EXPLORE_FILTER_POPULAR
      @stories = Story.top(nil, @tag)
    elsif filter_type == StoriesHelper::EXPLORE_FILTER_RECENT
      @stories = Story.recent(@tag)
    end

    @stories = @stories.where("title like '%#@query%'") unless @tag
    unless params[:page] == "all"
      @stories = @stories.paginate(page: params[:page])
    end

    @stories = @stories.where("user_id = #{params[:author_id]}") if params[:author_id]

    @stories = @stories.where("id > #{params[:higher_than_id]}") if params[:higher_than_id]
    @stories = @stories.where("id < #{params[:lower_than_id]}") if params[:lower_than_id]
    @stories = @stories.limit(params[:limit]) if params[:limit]

    respond_to do |f|
      f.js
      f.html
      f.json { render :json => StoryFormat.to_json(@stories, params) }
    end
  end

  def explore
    filter_type = params[:ft].blank? ? StoriesHelper::EXPLORE_FILTER_RECENT : params[:ft].to_i

    if filter_type == StoriesHelper::EXPLORE_FILTER_POPULAR
      @stories = Story.top(nil, params[:t]).paginate(page: params[:page])
    elsif filter_type == StoriesHelper::EXPLORE_FILTER_RECENT
      @stories = Story.recent(params[:t]).paginate(page: params[:page])
    end

    respond_to do |f|
      f.js
      f.html { render file: 'stories/explore' }
      f.json { render :json => StoryFormat.to_json(@stories, params) }
    end
  end

  def new
    render "new"
  end

  def show
    @story = Story.unscoped.find(params[:id])

    unless @story.published
      raise Onemyday::AccessDenied unless current_user? @story.user
    end

    @story.views.build(date: DateTime.now).save!

    respond_to do |f|
      f.html
      f.json {
        render :json => StoryFormat.to_json(@story, params)
      }
    end
  end

  def create
    @story = @current_user.stories.build(params[:story])
    @story.save

    respond_to do |t|
      t.js { render json: @story.id }
    end
  end

  def upload_photo
    @story = @current_user.stories.unscoped.find(params[:story_id])

    story_photo = StoryPhoto.create story_id: @story.id, photo: params[:story_photo][:photo], orientation: :center
    @story.story_elements.build element: story_photo, element_order: params[:element_order]
    @story.save

    @story_photos = @story.story_photos

    render 'uploaded_photos', layout: nil
  end

  def publish
    @story = @current_user.stories.unscoped.find(params[:story][:id])

    # do only when story goes from draft to published state
    unless @story.published
      @story.created_at = DateTime.now
      @current_user.followers.each do |follower|
        ActivityTracking.track @story, follower
      end
    end

    if @story.has_photos && @story.update_attributes(params[:story])
      if params[:crosspost_facebook].present? && params[:crosspost_facebook].to_bool &&
          params[:story][:published].to_bool && @current_user.has_facebook?
        pic = @story.story_photos.first.photo.url(:side) # paperclip with s3 will return full url here.
        @current_user.facebook.put_wall_post(@story.title, {name: "onemyday.co", link: story_url(@story), picture: pic})
      end
      redirect_to @story
    else
      render "new"
    end
  rescue Koala::Facebook::APIError => e
    logger.info e.message
    redirect_to story_url(@story) + "#showFacebookNoRights"
  end

  def like
    story = Story.find(params[:story_id])
    like = story.likes.build(user_id: current_user.id)
    like.save!
    ActivityTracking.track like, story.user
    render nothing: true
  end

  def unlike
    Story.find(params[:story_id]).likes.find_by_user_id(current_user.id).destroy
    render nothing: true
  end

  def destroy
    @story = Story.unscoped.find(params[:id])

    raise Onemyday::AccessDenied unless current_user? @story.user

    @story.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to current_user }
    end
  end

  def edit
    @story = Story.unscoped.find(params[:id])

    raise Onemyday::AccessDenied unless current_user? @story.user
  end

  def comments
    comments = Story.find(params[:id]).comments
    respond_to do |f|
      f.json { render json: comments.to_json }
    end
  end

  def likes
    likes = Story.find(params[:id]).likes
    respond_to do |f|
      f.json { render json: likes.to_json }
    end
  end

end

app/helpers/stories_helper.rb
module StoriesHelper

  EXPLORE_FILTER_POPULAR = 1
  EXPLORE_FILTER_RECENT = 2

  include Faker

  def get_lorem
    Faker::Lorem.sentence 25
  end

end

app/views/stories/_list_stories.slim
- if stories && stories.any?
  div#storiesContainer.storiesContainer
    = render "stories/list_stories_inner", stories: stories
- elsif defined?(empty_message) && empty_message
  span.noStoriesMessage = empty_message

app/views/stories/_list_stories_inner.slim
- stories && stories.each do |story|
  = render "stories/story", story: story

app/views/stories/_photo_upload_button.slim
input#storyId.storyId name="story_id" type="hidden" value="#{story_id}"
div.uploadError.alert.alert-error.hide
div#customProgressBar.progress.progress-striped.active
  div.bar style="width: 0"
  div.barText
span.btn.btn-large.f18.fileinput-button
  = t '.add_photo'
  input.photoUploadButton type="file" name="story_photo[photo]" multiple="multiple" data-url="#{upload_story_photo_path}"

app/views/stories/_story.slim
- if story.published?
  - image_dims = story.story_photos.first.photo_dimensions[:thumb]
  - own = current_user && story.user.id == current_user.id
  div class="smallStory relative #{'own' if own}" id="story#{story.id}" style="width: #{image_dims[:width]}px;"
    a href="#{story_path story}"
      div.image
        img src="#{story.story_photos.first.photo.url :thumb}" style="height:#{image_dims[:height]}px; width: #{image_dims[:width]}px;"
    div.text
      a href="#{story_path story}"
        div.title = story.title
      div.social
        i.icon-eye-open
        span = story.views.size.to_s
        i.icon-heart
        span = story.likes.size.to_s
        i.icon-comment
        span = story.comments.size
      div.date
        '@ #{story.date_nice_text} #{t '.by_html'} #{link_to story.user.name, story.user}
    div.imageHoverMenu.btn-group.hide
      = link_to t('.edit'), edit_story_path(story.id), class: "btn"
      = link_to t('.delete'), story_path(story.id), method: "delete", confirm: "Are you sure?", class: "btn", remote: true
- else
  div.smallStory.unpublished.relative id="unpublished#{story.id}" style="width: 300px;"
    - if story.story_photos.any?
      - image_dims = story.story_photos.first.photo_dimensions[:thumb]
      div.image
        img src="#{story.story_photos.first.photo.url :thumb}" style="height:#{image_dims[:height]}px; width: #{image_dims[:width]}px;"
    - else
      a href="#{story_path story}"
        div.image style="height:300px; width: 300px;"
          span No Image
    div.text
      a href="#{story_path story}"
        div.title #{story.title} (#{t '.draft'})
    div.imageHoverMenu.btn-group.hide
      = link_to t('.edit'), edit_story_path(story.id), class: "btn"
      = link_to t('.delete'), story_path(story.id), method: "delete", confirm: "Are you sure?", class: "btn", remote: true

app/views/stories/_story_edit.slim
= render 'shared/error_messages'

input#noStoryTitle type="hidden" value="#{t '.no_story_title'}"
input#noStoryDate type="hidden" value="#{t '.no_story_date'}"
input#defaultStoryText type="hidden" value="#{t '.default_story_text'}"
input#storyPhotoPath type="hidden" value="#{story_photo_path(-1)}"

h1.onemyday-header #{story ? "#{t '.edit_story'}" : "#{t '.tell_story'}"}

/ Upload photo form
div#photoUploadDiv
  = form_tag stories_path, id: "storyForm", remote: true do
    div
      label = t '.title'
      input#photoUploadStoryTitle type="text" name="story[title]" value="#{story.title if story}"
    div style="margin-top:15px"
      label = t '.tags'
      input#photoUploadTags name="story[tag_list]" value="#{story.tag_list if story}" style="width:200px"
      div.tagExp = t '.tags_desc'
    div style="clear:both"

    - if (!story || !story.published) && (current_user.has_facebook? || current_user.has_twitter?)
      div.crosspost
        label.mr10.tooltipize title='#{t '.crosspost_exp'}' data-placement='left' = t '.crosspost'
        - if current_user.has_facebook?
          input#crosspostFacebook.facebookAuth.tooltipize type="button" title='#{t '.facebook_share'}' data-placement='bottom' style="margin-right:10px;"
        - if current_user.has_twitter?
          input#crosspostTwitter.twitterAuth.tooltipize type="button" title='#{t '.twitter_share'}' data-placement='bottom'

    div.delim

  span#storySaveExp.hide.explanation = t ".story_saved_in_drafts"

  div.uploadButtonDiv
    = render 'photo_upload_button', story_id: (story.id if story)

/ Story
div#story.edit
  / Uploaded photos placeholder
  div#photoDiv

  / Story groups placeholder and misc.
  / This part of template is hidden and used only in js
  div#leftRightGroup.row.hide
    div.imagePlace.span55
    div.span0
    div.textPlace.span55
      div.time
      pre.text
  div#rightLeftGroup.row.hide
    div.textPlace.span55
      div.time
      pre.text
    div.span0
    div.imagePlace.span55
  div#centerGroup.row.hide
    div.row
      div.imagePlace.span12
    div.row.mt10
      div.textPlace.span12
        div.time
        pre.text
    div.row.mt10
      div.span0
  div#imageHoverMenuPlaceholder.imageHoverMenu.hide
    span.btn-group data-toggle="buttons-radio"
      button.leftOrientation.btn data-left="#{t '.left'}" data-side="#{t '.side'}" = t '.left'
      button.centerOrientation.btn = t '.center'
      button.rightOrientation.btn = t '.right'
    span.textControl.btn-group
      button.hasText.active.btn = t '.text'
    span.flowControl.btn-group
      button.moveUp.btn &uarr;
      button.moveDown.btn &darr;
    span.remove.btn-group
      a.removePhoto.btn href="#" data-href="#{story_photo_path(-1)}" data-remote="true" data-method="delete" data-confirm="Are you sure?": i.icon-remove

div#storyPublish class="#{"hide" unless story}"
  - if story
    - @story_photos = story.story_photos
    = render file: "stories/uploaded_photos"
  div style="clear:both"
  - publish = t '.publish'
  - save = t '.save'
  - save_as_draft = t '.save_as_draft'
  - move_to_drafts = t '.move_to_drafts'
  div.uploadButtonDiv
    = render 'photo_upload_button', story_id: (story.id if story)
    input#storyDraftButton.btn.ml10.btn-large.f18 type="button" data-publish-path="#{publish_path}"  value="#{story ? (story.published? ? move_to_drafts : save) : save_as_draft}"
  input#storyPublishButton.btn.fl.btn-large.btn-foxtrot.f18 type="button" data-publish-path="#{publish_path}" value="#{story ? (story.published? ? save : publish) : publish}"

app/views/stories/destroy.js.erb
<% if !@story.published %>
$("#unpublished<%= @story.id %>").fadeOut(function () {
  $(this).remove();
  $('#storiesContainer').masonry("option", {isAnimated: true}).masonry("reload")
          .masonry("option", {isAnimated: false});
});

if ($("#unpublishedCount")[0]) {
  var oldCount = parseInt($("#unpublishedCount").html());
  var newCount = oldCount - 1;
  if (newCount <= 0 && $("#unpublishedTab")[0]) {
    $("#unpublishedTab").remove();
    $("#ownTab a").click();
  } else {
    $("#unpublishedCount").html(newCount);
  }
}
<% else %>
$("#story<%= @story.id %>").fadeOut();
<% end %>

app/views/stories/edit.slim
= render "story_edit", story: @story

app/views/stories/explore.slim
div.whiteHeader
  div.smallInnerContainer
    div#advSearch.homeTags.exploreTags data-url="#{explore_path}"
      div.ib
        h2.headerCaption = t '.pop'
        h2.headerCaption = t '.tags_html'

      div#tags.ib.onemyday-bgroup.btn-group data-toggle="buttons-radio"
        a class="btn #{'active' unless params[:t].present?}" href="#{explore_path}" = t '.all'
        - get_popular_tags.each do |tag|
          a{class="btn #{'active' if params[:t].present? && params[:t] == tag.name}"
          href="#{explore_path}?t=#{tag.name}" data-type="#{tag.name}"} #{tag.name.capitalize}

      div#filter.ib.fr.onemyday-bgroup.btn-group data-toggle="buttons-radio"
        a{class="btn #{'active' if params[:ft].to_i == StoriesHelper::EXPLORE_FILTER_POPULAR}"
        data-type="#{StoriesHelper::EXPLORE_FILTER_POPULAR}"} = t '.popular'
        a{class="btn #{'active' if params[:ft].blank? || params[:ft].to_i == StoriesHelper::EXPLORE_FILTER_RECENT}"
        data-type="#{StoriesHelper::EXPLORE_FILTER_RECENT}"} = t '.recent'

div.whiteHeaderContentSmall
  div#exploreStoriesContainer
    = render "stories/list_stories", stories: @stories, empty_message: t('stories.empty_message')

  div style="clear:both"
  = will_paginate @stories

app/views/stories/new.slim
div#newStory
  = render "story_edit", story: nil

app/views/stories/search.slim
div.whiteHeader
  div.smallInnerContainer
    div#searchInnerContainer data-url="#{search_stories_path}" data-query="#{u @query}"
      - search_text = @tag ? t('.with_tag') : t('.matching')
      - if @stories.any?
        h3.searchHeader.fl = t('.found', :stories => pluralize(@stories.count, t('.story'), t('.stories')), :search_text => search_text, :query => @tag ? @tag : @query)
      - else
        h3.searchHeader.fl = t('.not_found', :search_text => search_text, :query => @tag ? @tag : @query)

      div#filter.ib.fr.onemyday-bgroup.btn-group data-toggle="buttons-radio"
        a{class="btn #{'active' if params[:ft].to_i == StoriesHelper::EXPLORE_FILTER_POPULAR}"
        data-type="#{StoriesHelper::EXPLORE_FILTER_POPULAR}"} = t '.popular'
        a{class="btn #{'active' if params[:ft].blank? || params[:ft].to_i == StoriesHelper::EXPLORE_FILTER_RECENT}"
        data-type="#{StoriesHelper::EXPLORE_FILTER_RECENT}"} = t '.recent'

div.whiteHeaderContentSmall
  div#searchStoriesContainer
    = render 'list_stories', stories: @stories

  div style="clear:both"
  = will_paginate @stories

app/views/stories/show.slim
- provide(:title, @story.meta_description)
- provide(:meta_tags, facebook_like_meta(@story.title, story_url(@story.id), @story.story_photos.first.photo.url(:side))) if @story.story_photos.any?
- provide(:meta_description, @story.meta_description)
- provide(:meta_keywords, @story.meta_tags)

div#showFacebookNoRights.hide.alert
  = t ".no_facebook_right_1"
  br
  br
  = t ".no_facebook_right_2"

div.storyHeaderDiv
  - draftText = "<span class='storyHeaderDraft'>(#{t('.draft')})</span>"
  div.storyHeader.lobster #{@story.title} #{ raw(draftText) unless @story.published}

  div.storySubHeader
    ' #{@story.date_nice_text} #{t '.by_html'}
    a href="#{user_path @story.user.id}" = @story.user.name

  - if current_user? @story.user
    div.storyMenu
      a.btn.btn-super-small href="#{edit_story_path(@story.id)}" = t '.edit_story'

  div.storySubHeaderBorder

div#story
  - @story.story_elements.each do |story_element|
    - if story_element.element_type == "StoryPhoto"
      - story_photo = story_element.element
      - side_image_dims = story_photo.photo_dimensions[:side]
      - center_image_dims = story_photo.photo_dimensions[:center]
      - if story_photo.left?
        div#leftRightGroup class="row storyGroup #{'noText' unless story_photo.has_text}"
          div.imagePlace.span55
            img src="#{story_photo.photo.url(:side)}" style="height: #{side_image_dims[:height]}px" alt="#{story_photo.caption_for_alt}"
          div class="span0 #{'span0_hidden' unless story_photo.has_text}"
          div class="textPlace span55 #{'hide' unless story_photo.has_text}"
            div.time
              = story_photo.date_text
            - if story_photo.caption.present?
              pre.text
                = story_photo.caption
      - if story_photo.right?
        div#rightLeftGroup class="row storyGroup #{'noText' unless story_photo.has_text}"
          div class="textPlace span55 #{'hide' unless story_photo.has_text}"
            div.time
              = story_photo.date_text
            - if story_photo.caption.present?
              pre.text
                = story_photo.caption
          div class="span0 #{'span0_hidden' unless story_photo.has_text}"
          div.imagePlace.span55
            img src="#{story_photo.photo.url(:side)}" style="height: #{side_image_dims[:height]}px" alt="#{story_photo.caption_for_alt}"
      - if story_photo.center?
        div#centerGroup class="row storyGroup #{'noText' unless story_photo.has_text}" data-orientation="center"
          div.row
            div.imagePlace.span12
              img src="#{story_photo.photo.url(:center)}" style="width: #{center_image_dims[:width]}px; height:#{center_image_dims[:height]}px" alt="#{story_photo.caption_for_alt}"
          div.row.mt10
            div class="textPlace span12 #{'hide' unless story_photo.has_text}"
              div.time
                = story_photo.date_text
              - if story_photo.caption.present?
                pre.text
                  = story_photo.caption
          div.row.mt10
            div.span0
    - elsif story_element.element_type == "StoryText"
      - story_text = story_element.element
      pre.text
        = story_text.text

div.storyEnd
  div.header.lobster = t '.the_end'
  div.subHeader

- has_tags = @story.tags.any?
div class="grayBottomer #{'no_tags' unless has_tags}"
  div.innerContainer
    - if has_tags
      div.storyTags
        = t '.tags'
        - @story.tags.each do |tag|
          a.ml5 href="#{explore_path}?t=#{tag}" #{tag}

    div style='clear:both;'

    - if current_user
      - like = @story.likes.find_by_user_id current_user.id
      = form_tag like ? unlike_path : new_like_path, remote:true, class: "likeForm" do
        input type="hidden" name="story_id" value="#{@story.id}"
        a#storyLike.btn.btnLike data-submitable="true" data-like="#{t '.like'}" data-liked="#{t '.liked'}" class="#{like ? "btn-foxtrot" : ""}"
          span #{like ? t('.liked') : t('.like')}
    - else
      a#noUserLike.btn.btnLike href="#signInModal" data-toggle="modal" : span #{t('.like')}
    - if @story.likes.any?
      div#likeWrapper.likeWrapper
        div#likeBox.likeBox
          - (0...6).each do |i|
            - like = @story.likes[i]
            - break unless like
            a href="#{user_path like.user.id}"
              = image_tag like.user.avatar.url(:thumb), title: like.user.name, width: "32"
        div.likes
          i.icon-heart
          a#likeLink href="#likesModal" data-toggle="modal" = pluralize(@story.likes.size, t(".person"), t(".people"))
          = t '.like_count_desc_html'

      div#likesModal.fade.show_user_small.modal.hide
        button type="button" class="close" data-dismiss="modal" ×
        div.modal-header.open-sans
          h3 = t '.likes_header'
        div.modal-body
          - @story.likes.each do |like|
            = render 'shared/show_user_small', user: like.user

    div style='clear:both;'

div class="grayBottomerSpan #{'no_tags' unless has_tags}"

div.bottomShareMenu
  span.helpText = t ".share_story_text"
  div.fb-like data-send="false" data-width="450" data-show-faces="false" data-font="verdana" data-layout="button_count"
  a.twitter-share-button href="https://twitter.com/share" data-hashtags="onemyday" Tweet

div#commentsContainer
  - @story.comments.by_date.each do |comment|
    = render "/comments/comment", comment: comment, clazz: cycle("odd", "even")
  - if current_user
    = form_for Comment.new, remote:true, html:{id:"addCommentForm"} do |f|
      input type="hidden" name="story_id" value="#{@story.id}"
      div.addWrapper
        div.add
          = image_tag current_user.avatar.url(:small), class: "avatar-small"
          div.addTextWrapper
            = f.text_area :text, placeholder: t('.comment_placeholder'), class: "addText", id: "addCommentTextarea"
          = f.submit t('.send'), class: "btn submit fl", disabled: "disabled", id: "addCommentSubmit"
          br clear="both"

- unless current_user
  a#registerComments.btn href="#signInModal" data-toggle="modal" = t '.register_comments'